
= KieBase

The jBPM API allows you to first create a KIE base.
This KIE base should include all your process definitions that might need to be executed by that session.
To create a KIE base, use a KieHelper to load processes from various resources (for example from the classpath or from the file system), and then create a new KIE base from that helper.
The following code snippet shows how to create a KIE base consisting of only one process  definition (using in this case a resource from the classpath).

[source,java]
----

  KieHelper kieHelper = new KieHelper();
  KieBase kieBase = kieHelper
                    .addResource(ResourceFactory.newClassPathResource("MyProcess.bpmn"))
                    .build();
----

The ResourceFactory has similar methods to load files from file system, from URL, InputStream, Reader, etc.

ResourceFactory 也有相类似的方法可以从文件系统，URL，InputStream，Reader 等来源来加载文件。

This is considered manual creation of KIE base and while it is simple it is not recommended for real application development but more for try outs.
Following you'll find recommended and much more powerful way of building KIE base, KIE session and more - RuntimeManager.

这种方式被用来手动创建 KIE base，这种方式非常简单，但是不推荐正式环境使用，只适合学习时作为 DEMO 尝试。
